In [38]:
import numpy as np
import time

def read_matrix(filename):
    data = np.loadtxt(filename)
    L = int(data[0])
    A = data[1:1+L*L].reshape(L, L)
    b = data[1+L*L:1+L*L+L]
    return A, b

def determinant(A):
    # рекурсивное вычисление определителя
    n = A.shape[0]
    
    if n == 2:
        return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]
    
    det = 0
    for j in range(n):
        sign = (-1) ** j
        # Создаем минор
        M = np.delete(np.delete(A, 0, axis=0), j, axis=1)
        det += sign * A[0, j] * determinant(M)
    
    return det

# Метод Гаусса

In [39]:
# # тут как в лекции
# def gaussian_elimination(A, b):
#     n = len(b)
#     A = A.copy()
#     b = b.copy()

#     # прямой ход
#     for k in range(n):
#         # поиск ПЕРВОЙ строки с A[k, k] != 0
#         row = k
#         while row < n and A[row, k] == 0:
#             row += 1
#         if row == n:
#             raise ValueError("Матрица вырождена")
#         if row != k:
#             A[[k, row]] = A[[row, k]]
#             b[[k, row]] = b[[row, k]]

#         # нормализация строки k
#         divisor = A[k, k]
#         A[k] /= divisor
#         b[k] /= divisor

#         # исключение переменной
#         for i in range(k+1, n):
#             factor = A[i, k]
#             A[i] -= factor * A[k]
#             b[i] -= factor * b[k]

#     # обратный ход
#     x = np.zeros(n)
#     for m in range(n-1, -1, -1):
#         x[m] = b[m] - np.dot(A[m, m+1:], x[m+1:])
    
#     return x

In [40]:
def gaussian_elimination(A, b):
    n = len(b)
    # создает копии для сохранения исходных данных
    A = A.copy()
    b = b.copy()
    
    # прямой ход
    for k in range(n):
        # поиск главного элемента
        max_row = k
        for i in range(k+1, n):
            if abs(A[i, k]) > abs(A[max_row, k]):
                max_row = i
        
        # перестановка строк
        if max_row != k:
            A[[k, max_row]] = A[[max_row, k]]
            b[[k, max_row]] = b[[max_row, k]]
        
        # нормализация текущей строки
        divisor = A[k, k]
        if divisor == 0:
            raise ValueError("Матрица вырождена")
        
        A[k] /= divisor
        b[k] /= divisor
        
        # исключение переменной
        for i in range(k+1, n):
            factor = A[i, k]
            A[i] -= factor * A[k]
            b[i] -= factor * b[k]
    
    # обратный ход
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = b[i] - np.dot(A[i, i+1:], x[i+1:])
    
    return x

In [41]:
# import numpy as np

# def gaussian_elimination(A, b):
#     n = len(b)
#     # создает копии для сохранения исходных даных
#     A = A.copy()
#     b = b.copy()
    
#     print("исходная расширеная матрица:")
#     print_extended_matrix(A, b)
#     print()
    
#     # прямой ход
#     for k in range(n):
#         print(f"Шаг {k+1}:")
        
#         # поиск главного элемента
#         max_row = k
#         for i in range(k+1, n):
#             if abs(A[i, k]) > abs(A[max_row, k]):
#                 max_row = i
        
#         # перестановка строк
#         if max_row != k:
#             print(f"перестановка строк {k+1} и {max_row+1}")
#             A[[k, max_row]] = A[[max_row, k]]
#             b[[k, max_row]] = b[[max_row, k]]
#             print("после перестановки:")
#             print_extended_matrix(A, b)
        
#         # нормализация текущей строки
#         divisor = A[k, k]
#         if divisor == 0:
#             raise ValueError("матрица вырождена")
        
#         print(f"нормализация строки {k+1} (деление на {divisor:.3f})")
#         A[k] /= divisor
#         b[k] /= divisor
#         print("после нормализации:")
#         print_extended_matrix(A, b)
        
#         # исключение переменой
#         for i in range(k+1, n):
#             factor = A[i, k]
#             if factor != 0:
#                 print(f"исключение переменой из строки {i+1} (вычитание {factor:.3f} * строки {k+1})")
#                 A[i] -= factor * A[k]
#                 b[i] -= factor * b[k]
        
#         print("после исключения:")
#         print_extended_matrix(A, b)
#         print("-" * 50)
    
#     print("матрица после прямого хода (треугольный вид):")
#     print_extended_matrix(A, b)
#     print()
    
#     # обратный ход
#     x = np.zeros(n)
#     for i in range(n-1, -1, -1):
#         x[i] = b[i] - np.dot(A[i, i+1:], x[i+1:])
    
#     print("результат обратного хода:")
#     for i in range(n):
#         print(f"x[{i+1}] = {x[i]:.6f}")
    
#     return x

# def print_extended_matrix(A, b):
#     """вывод расширеной матрицы в красивом формате"""
#     n = len(b)
#     for i in range(n):
#         # вывод элементов матрицы A
#         row_str = "["
#         for j in range(n):
#             row_str += f"{A[i, j]:8.3f}"
#         row_str += f" | {b[i]:8.3f}]"
#         print(row_str)

In [42]:

for size in [3, 5, 11]:
    A, b = read_matrix(f'Matrix{size}.txt')
    
    x_gauss = gaussian_elimination(A, b)
    
    det = determinant(A)
    error = np.linalg.norm(np.dot(A, x_gauss) - b)
    x_lib = np.linalg.solve(A, b)
    det_lib = np.linalg.det(A)
    print(f"Размер {size}x{size}:")
    print(f"Определитель: {det}")
    print(f"Определитель (библиотечный): {det_lib}")
    print(f"Погрешность: {error:.2e}")
    print(x_gauss)
    print("Библиотечное решение:")
    print(x_lib)
    print()



Размер 3x3:
Определитель: -1.0
Определитель (библиотечный): -1.0
Погрешность: 0.00e+00
[ 2.  3. -1.]
Библиотечное решение:
[ 2.  3. -1.]

Размер 5x5:
Определитель: 1764.0
Определитель (библиотечный): 1764.0000000000005
Погрешность: 0.00e+00
[1.06575964 0.59863946 1.29931973 1.63945578 2.19954649]
Библиотечное решение:
[1.06575964 0.59863946 1.29931973 1.63945578 2.19954649]

Размер 11x11:
Определитель: 6946360.093800559
Определитель (библиотечный): 6946360.093800582
Погрешность: 1.34e-13
[   1.2248859     6.02546905    2.62338574    1.81949873  -77.85810089
    2.33244982   58.41264575   -2.00320203 -177.39303784    7.57192315
  142.66658862]
Библиотечное решение:
[   1.2248859     6.02546905    2.62338574    1.81949873  -77.85810089
    2.33244982   58.41264575   -2.00320203 -177.39303784    7.57192315
  142.66658862]



# Метод прогонки

In [43]:
def thomas_algorithm(A, b):
    n = len(b)
    # создает копии
    A = A.copy()
    b = b.copy()
    
    # прямой ход
    for i in range(1, n):
        factor = A[i, i-1] / A[i-1, i-1]
        A[i, i] -= factor * A[i-1, i]
        b[i] -= factor * b[i-1]
        A[i, i-1] = 0  # обнуляет элемент
    
    # обратный ход
    x = np.zeros(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - A[i, i+1] * x[i+1]) / A[i, i]
    
    return x


In [44]:
# import numpy as np

# def thomas_algorithm(A, b):
#     n = len(b)
    
#     # печатает исходную матрицу и вектор
#     print("исходная матрица A:")
#     print(A)
#     print("\nисходный вектор b:")
#     print(b)
#     print("\n" + "="*50)
    
#     # создает копи
#     A = A.copy()
#     b = b.copy()
    
#     # прямой ход
#     print("\nпрямой ход:")
#     for i in range(1, n):
#         print(f"\nШаг {i}:")
#         print(f"матрица перед преобразованием:")
#         print(A)
#         print(f"вектор b: {b}")
        
#         factor = A[i, i-1] / A[i-1, i-1]
#         print(f"множитель для строки {i}: {factor}")
        
#         A[i, i] -= factor * A[i-1, i]
#         b[i] -= factor * b[i-1]
#         A[i, i-1] = 0  # обнуляет элемент
        
#         print(f"матрица после преобразования:")
#         print(A)
#         print(f"вектор b: {b}")
    
#     print("\n" + "="*50)
#     print("матрица после прямого хода (верхняя треугольная форма):")
#     print(A)
#     print("вектор b после прямого хода:")
#     print(b)
    
#     # обратный ход
#     print("\n" + "="*50)
#     print("обратный ход:")
#     x = np.zeros(n)
#     x[-1] = b[-1] / A[-1, -1]
#     print(f"x[{n-1}] = {b[-1]} / {A[-1, -1]} = {x[-1]}")
    
#     for i in range(n-2, -1, -1):
#         print(f"\nвычисление x[{i}]:")
#         print(f"x[{i}] = ({b[i]} - {A[i, i+1]} * {x[i+1]}) / {A[i, i]}")
#         x[i] = (b[i] - A[i, i+1] * x[i+1]) / A[i, i]
#         print(f"x[{i}] = {x[i]}")
    
#     print("\n" + "="*50)
#     print("результат:")
#     return x



In [45]:

for size in [3, 5, 11]:
    A, b = read_matrix(f'Tridiagonal{size}.txt')
    
    x_thomas = thomas_algorithm(A, b)
    det = determinant(A)

    error = np.linalg.norm(np.dot(A, x_thomas) - b)
    x_lib = np.linalg.solve(A, b)
    det_lib = np.linalg.det(A)
    print(f"Размер {size}x{size}:")
    print(f"Погрешность: {error:.2e}")
    print(f"Определитель: {det}")
    print(f"Определитель (библиотечный): {det_lib}")
    print(x_thomas)
    print("Библиотечное решение:")
    print(x_lib)
    print()

Размер 3x3:
Погрешность: 4.44e-16
Определитель: 4.0
Определитель (библиотечный): 4.0
[5.00000000e-01 1.48029737e-16 1.50000000e+00]
Библиотечное решение:
[5.00000000e-01 1.48029737e-16 1.50000000e+00]

Размер 5x5:
Погрешность: 4.44e-16
Определитель: 6.0
Определитель (библиотечный): 6.0
[5.00000000e-01 1.48029737e-16 1.50000000e+00 0.00000000e+00
 2.50000000e+00]
Библиотечное решение:
[5.00000000e-01 1.48029737e-16 1.50000000e+00 0.00000000e+00
 2.50000000e+00]

Размер 11x11:
Погрешность: 1.63e-14
Определитель: 9351766146.938484
Определитель (библиотечный): 9351766146.938494
[1.81805283 1.69229184 2.17164178 2.37651691 2.63422248 2.81684013
 3.01244564 3.09343091 3.41584711 2.97198534 4.70872856]
Библиотечное решение:
[1.81805283 1.69229184 2.17164178 2.37651691 2.63422248 2.81684013
 3.01244564 3.09343091 3.41584711 2.97198534 4.70872856]



# Сравнение


In [46]:
print("\n" + "="*20 + " СРАВНЕНИЕ МЕТОДОВ " + "="*20)

A, b = read_matrix('Tridiagonal3.txt')

start_time = time.time()
x_gauss = gaussian_elimination(A, b)
gauss_time = time.time() - start_time

start_time = time.time()
x_thomas = thomas_algorithm(A, b)
thomas_time = time.time() - start_time

print(f"\nСравнение методов для трехдиагональной системы 3x3:")
print("Решение методом Гаусса:")
for i, val in enumerate(x_gauss):
    print(f"x_{i+1} = {val:.6f}")

print("Решение методом прогонки:")
for i, val in enumerate(x_thomas):
    print(f"x_{i+1} = {val:.6f}")

print(f"Метод Гаусса: {gauss_time:.6f} сек")
print(f"Метод прогонки: {thomas_time:.6f} сек")
print(f"Разница во времени: {gauss_time-thomas_time:.6f} сек")
        


==================== СРАВНЕНИЕ МЕТОДОВ ====================

Сравнение методов для трехдиагональной системы 3x3:
Решение методом Гаусса:
x_1 = 0.500000
x_2 = 0.000000
x_3 = 1.500000
Решение методом прогонки:
x_1 = 0.500000
x_2 = 0.000000
x_3 = 1.500000
Метод Гаусса: 0.000000 сек
Метод прогонки: 0.000000 сек
Разница во времени: 0.000000 сек
